### PR TITLE
Prevent hang when throwing out of adios constructor in MPI.

### LINKED ISSUE #1938: Flexible Init with/without config file cannot be added to applications
I want to recover from failure of not finding the xml config and just initialize with default. This results in non-zero ranks hanging in broadcast. 
```
    try {
        ad =  new adios2::ADIOS("adios2_config.xml", world, adios2::DebugON);
    } catch (std::ios_base::failure &e) {
        ad = new adios2::ADIOS(world, adios2::DebugON);
    }
```

When the config file is not present, rank 0 throws an exception, which is caught with the catch statement and then a default init is called. However, all other processes are stuck in a broadcast call for receiving the file content from rank 0 in adiosXML.cpp::ParseConfigXML()

Suggestion: in adiosComm.cpp::Comm::BroadcastFile, the exception should be caught (on rank 0) and then the broadcast should happen with some constant string that indicates error. After that all process should throw the same exception.

### PR DESCRIPTION
**Pull request by NAThompson**
Fixes #1938

### CODE REVIEW

File: source/adios2/core/ADIOS.cpp [hunk 1]
```diff
@@ -64,6 +65,12 @@ ADIOS::ADIOS(const std::string configFile, helper::Comm comm,
 {
     if (!configFile.empty())
     {
+        std::ifstream f(configFile.c_str());
```
Comment (chuckatkins) [inline source/adios2/core/ADIOS.cpp]: `adios2sys::SystemTools::FileExists` from `#include <adios2sys/SystemTools.hxx>`

File: testing/adios2/engine/bp/TestBPNoXMLRecovery.cpp [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+#endif
+
+int main(int argc, char *argv[])
+{
+    int rank = 0;
+#ifdef ADIOS2_HAVE_MPI
+    int size = 1;
+    MPI_Init(&argc, &argv);
+    MPI_Comm_rank(MPI_COMM_WORLD, &rank);
+    MPI_Comm_size(MPI_COMM_WORLD, &size);
```
Comment (chuckatkins) [inline testing/adios2/engine/bp/TestBPNoXMLRecovery.cpp]: size isn't actually being used here and can be removed
