### PR TITLE
zfp: fix version compatibility for 1.0+

### LINKED ISSUE #3303: Compatibility with ZFP 1.0
**Describe the bug**

[ZFP 1.0](https://github.com/LLNL/zfp/releases/tag/1.0.0) is out this week, but cmake rejects it (possibly correctly) as incompatible with the desired target of 0.5.1:

```
CMake Error at cmake/DetectOptions.cmake:94 (find_package):
Could not find a configuration file for package "ZFP" that is compatible
with requested version "0.5.1".

The following configuration files were considered but not accepted:
  $PREFIX/lib/cmake/zfp/zfp-config.cmake, version: 1.0.0
Call Stack (most recent call first):
 CMakeLists.txt:165 (include)
```

**To Reproduce**
1. install zfp 1.0
2. try to configure adios2 with `-DADIOS2_USE_ZFP=ON`
3. see `Could not find a configuration file for package "ZFP" that is compatible`

**Expected behavior**

Build succeeds.

**Desktop (please complete the following information):**
 - OS/Platform: Ubuntu 20.04
 - Build: cmake 3.23, zfp 1.0.0

**Additional context**

Building on [conda-forge](https://github.com/conda-forge/adios2-feedstock)

**Following up**

### PR DESCRIPTION
**Pull request by chuckatkins**
Allow cmake to find zfp >= 1.0.  Also adjusts the minimum requirement to
0.5.3 for execution policy selection.

Fixes #3303

### CODE REVIEW

**Comment by chuckatkins** [comment]
@ax3l

**Review by ax3l — APPROVED** [review]
Awesome, thank you!

File: source/adios2/operator/compress/CompressZFP.cpp [hunk 1]
```diff
@@ -302,7 +298,6 @@ zfp_stream *GetZFPStream(const Dims &dimensions, DataType type,
     auto itPrecision = parameters.find("precision");
     const bool hasPrecision = itPrecision != parameters.end();
 
-#if ZFP_VERSION_RELEASE > 1
```
Comment (ax3l) [inline source/adios2/operator/compress/CompressZFP.cpp:305]: @chuckatkins is this also valid for 0.5.3?
